thaw-ui/thaw

demo_markdown/docs/auto_complete/mod.md
thaw/src/auto_complete/mod.rs

Hi @luoxiaozero here is my monkey-patched version of AutoComplete - I needed to support free input and not only selection from `options`.
Maybe this could be made into an option of `AutoComplete`, what do you think?

feat: allow free input in AutoComplete

---

demo_markdown/docs/input_number/mod.md
thaw/Cargo.toml
thaw/src/input_number/mod.rs

Hello @luoxiaozero 
Added range with min/max props to InputNumber component.
When the input value reaches the limit, the plus/minus icon will be disabled.
If it goes out of range, the component will be invalid and will automatically fall within the range on blur.

feat: Add min/max props into InputNumber

---

thaw_utils/src/signals/model.rs

Previously there was no way to create a `Model` from a `Signal` and `WriteSignal`, despite those being the internal types used within the `Model`. This PR adds this implementation.

Impl from `Signal` and `WriteSignal` for `Model`

---

demo/src/components/site_header.rs

The branch switcher dropdown should probably not have a fixed width.

Remove fixed width on version switcher

---

demo/src/pages/nav_bar/mod.rs
demo_markdown/docs/drawer/mod.md
demo_markdown/src/lib.rs
demo_markdown/src/markdown/code_block.rs
demo_markdown/src/markdown/mod.rs
thaw/src/back_top/mod.rs
thaw/src/back_top/theme.rs
thaw_utils/src/class_list.rs
thaw_utils/src/dom/get_scroll_parent.rs
thaw_utils/src/hooks/use_click_position.rs
thaw_utils/src/hooks/use_lock_html_scroll.rs
thaw_utils/src/hooks/use_next_frame.rs
thaw_utils/src/throttle.rs

According to https://github.com/rust-lang/rust/issues/48919, a method with this name may be added to the standard library in the future, which may cause ambiguity or even change the behavior. So it would be better to use fully qualified syntax here:
```diff
-<Button on_click=Callback::new(move |_| open.call(DrawerPlacement::Top))>"Top"</Button>
+<Button on_click=Callback::new(move |_| leptos::Callable::call(&open, DrawerPlacement::Top))>"Top"</Button>
```
Also, some clippy lints also have been fixed separately 🍔

Use fully qualified syntax in the example of `Drawer`

---

thaw/src/message/mod.rs

It should be the ✓ for success and the ✗ for error to make more intuitive sense.

fix(Message): interchange the icons of `MessageVariant::Success` and `MessageVariant::Error`

---

thaw/src/scrollbar/mod.rs

Hi,
I'm getting following errors from the scrollbar component:
```
repo/thaw/thaw/src/scrollbar/mod.rs:160:22:
could not set stored value
Stack:
@http://localhost:1420/twili-recipes-ui-185fc906b025bcf7.js:507:26
twili_recipes_ui-6eb6c11dcaa98b55.wasm.wasm-function[console_error_panic_hook::Error::new::he0c5f77003cc61aa]@[wasm code]
twili_recipes_ui-6eb6c11dcaa98b55.wasm.wasm-function[console_error_panic_hook::hook_impl::h6a0063ad36e0b326]@[wasm code]
twili_recipes_ui-6eb6c11dcaa98b55.wasm.wasm-function[console_error_panic_hook::hook::hfdf1575546c7f72c]@[wasm code]
twili_recipes_ui-6eb6c11dcaa98b55.wasm.wasm-function[core::ops::function::Fn::call::h886484cdfff24eff]@[wasm code]
twili_recipes_ui-6eb6c11dcaa98b55.wasm.wasm-function[std::panicking::rust_panic_with_hook::h3fe0a99cc3d59b9d]@[was …
```

fix scrollbar panic

---

thaw/src/icon/icon.css
thaw/src/message/message.css

I've just noticed the same issue as described here (https://github.com/thaw-ui/thaw/issues/190) and tracked it down to tailwindcss.  In the output.css generated by it we have:
```
/*
1. Make replaced elements `display: block` by default. (https://github.com/mozdevs/cssremedy/issues/14)
2. Add `vertical-align: middle` to align replaced elements more sensibly by default. (https://github.com/jensimmons/cssremedy/issues/14#issuecomment-634934210)
This can trigger a poorly considered lint error in some tools but is included by design.
*/
img,
svg,
video,
canvas,
audio,
iframe,
embed,
object {
display: block;
/* 1 */
vertical-align: middle;
/* 2 */
}
```
Your recent change sets the display to inline-block (https://github.com/thaw-ui/thaw/commit/983e85728a21f0443f1ef0eb02b5da81c54b5ed4) and this …

icon missaligment in message fix

---

demo_markdown/docs/modal/mod.md
thaw/src/modal/mod.rs

Hi, added class to the modal component. Without it I couldn't make it responsive and fit nicely on mobile. 
I tested the component but I'm getting errors when I try to build the demo page:
```
error[E0282]: type annotations needed for `Box<_>`
--> /opt/cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.30/src/format_description/parse/mod.rs:83:9
|
83 |     let items = format_items
|         ^^^^^
...
86 |     Ok(items.into())
|              ---- type must be known at this point
|
help: consider giving `items` an explicit type, where the placeholders `_` are specified
|
83 |     let items: Box<_> = format_items
|              ++++++++
```
Hope the markdown is ok. 
Any idea what is causing the error? I'm on rust 1.80.0-nightly.

add class to modal

---

demo_markdown/docs/input/mod.md
demo_markdown/docs/input_number/mod.md
thaw/src/input/mod.rs
thaw/src/input_number/mod.rs
thaw_utils/src/optional_prop.rs

This PR tries to resolve issue https://github.com/thaw-ui/thaw/issues/129 by adding optional callbacks to Input and InputNumber components. The parser callback converts user input to the desired signal format, while the formatter callback presents the signal value to the user. You can check it working in the Docs.
Following the suggested implementation I've added the parser to the onchange event. There was the need to clone the parser in order to be consumed by two closures. Please, feel free to give advice on how to avoid the cloning.
Thank you!

Added parser and formatter props to input and input_number components

---

demo_markdown/docs/menu/mod.md
thaw/src/menu/menu-item.css

Fixing small issue with menu css and trying to improve the demo page.
I have an issue with the on_select callback. In the first example it causes `caught RuntimeError: unreachable executed` again. 
But second example on https://next-thawui.vercel.app/components/toast also doesn't work failing with similar error. So I guess it's toast issue and not the menu page? Can you please check?

fix menu disabled, add toast actions to demo page

---

demo_markdown/docs/_guide/server_sider_rendering.md

I was trying thaw and stumble accross an error `cannot call wasm-bindgen imported functions on non-wasm targets` when trying to serve my basic leptos page. It turns out the feature need to be added to those lists on `Cargo.toml` for thaw to work. This might be obvious to more experienced devs in rust, but me being a newbie couldn't solved it by myself.

Improving server side rendering docs to include feature

---

thaw/src/theme/mod.rs

`CommonTheme` and others need to be accessible for customizing colors. This now works:
```rust
#[component]
fn TheProvider(children: Children) -> impl IntoView {
let base_theme = Theme::light();
let custom_theme = Theme {
common: thaw::CommonTheme {
color_primary: "var(--variable-set-in-style-css-file)".to_string(),
..base_theme.common
},
..base_theme
};
let theme = create_rw_signal(custom_theme);
view! {
<ThemeProvider theme>
{children()}
</ThemeProvider>
}
}
```

fix: allow creating custom theme

---

thaw/src/combobox/combobox.rs

Clicking the ExpandIcon of the Combobox does not close the popup window

fix: clicking the ExpandIcon of the Combobox does not close the popup

---

Cargo.toml
thaw/Cargo.toml
thaw_components/Cargo.toml
thaw_macro/Cargo.toml
thaw_utils/Cargo.toml

This declares the MSRV globally at package level, even though the dependency seems to be only with thaw_components today, to make the setting easier to manage (like Leptos does).
Leptos 0.7.0-gamma2 exposes a MSRV of 1.76, but with 1.78 and earlier:
```
Compiling thaw_components v0.2.0-beta3 (https://github.com/thaw-ui/thaw?rev=0c5cb880950ff2229ab2762bfa64a900b70a857d#0c5cb880)
error[E0716]: temporary value dropped while borrowed
--> /home/user/.cargo/git/checkouts/thaw-057be4168b51a04a/0c5cb88/thaw_components/src/teleport/mod.rs:15:14
|
11 |           let mount = if let Some(el) = mount.as_ref() {
|               ----- borrow later stored here
...
15 |               &document()
|  ______________^
16 | |                 .body()
17 | |                 .expect("body element to exist")
18 | …
```

Declare MSRV of 1.79

---

examples/ssr_axum/Cargo.toml
thaw_utils/src/signals/model.rs

Proposal for #271, targets the 0.3  branch.
What we are trying to achieve: Make a more generic interface for `Model<T>`. This specifically addresses the issue of `From<(Signal, SignalSetter)>`.
How we did it: Switch the internals of `Model<T>` from `WriteSignal<T>` to `SignalSetter<T>`. This leads us to having to implement `SignalUpdate<T>` for `Model<T>` manually.
How we tested it: `cargo test` seems to take issue with the doctests at compile time, which I do not understand (yet). Other tests seem to work fine fine.

feat: Make Model<T> use SignalSetter instead of WriteSignal

---

thaw/src/input/docs/mod.md
thaw/src/input/mod.rs

Adds readonly and size props to the input component. The size prop is the input [size](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/size) attribute.

feat: add `readonly` and `size` props to `Input`

---

thaw/src/drawer/docs/mod.md
thaw/src/drawer/drawer_body.rs

I have a case where I'd line an inner element within the DrawerBody to be scrollable, and the drawerbody itself does not need to be scrollable.
To solve this, I've added an optional `scrollable` prop to the `DrawerBody`.

feat: add `scrollable` prop to `DrawerBody`

---

thaw/src/field/rule.rs

The `RuleValidator` type has issues with leptos 0.7 due to the lack of Send + Sync trait bounds.

feat: add `Send` + `Sync` bounds to `RuleValidator`

---

thaw/src/avatar/mod.rs

Implements initials name function

feat: implement initials name

---

demo/src/components/site_header.rs
thaw/src/menu/docs/mod.md
thaw/src/menu/menu_item.rs
thaw/src/menu/mod.rs

Most of the time I found that I would want to use an enum for the MenuItem's, so this PR generifies Menu/MenuItem so that any type which satisfies Clone can be used as value.
Of course with the generics we hit https://github.com/leptos-rs/leptos/issues/3200#issuecomment-2483121002 so the type needs to be specified when creating the MenuItem's.
I wonder if `value` even needs to be a `Signal` or if it could be a simple value?

feat: generify menu

---

thaw/src/combobox/common/listbox.rs

when using auto complete as a search box it would be nice to be able to enter a space. I think this might be a compromise that allows both space to be used to open and  select items as well as to be used as a space when once the listbox is open.

allow typing space

---

thaw_utils/src/dom/ssr_mount_style.rs

Per #427 this adds an implementation of `hydrate_async` instead of falling back to the default non-async implementation.

feat: add hydrate_async implementation. closes #427

---

thaw_components/src/binder/use_binder.rs

As #415 mentions, the correct position of e.g. popovers is computed incorrectly if the window itself is scrollable, since Element.getBoundingClientRect is relative to the viewport. To fix that, we need to add the scroll offsets of the window itself to the DomRect.
This PR adds a method `get_true_rect` that does exactly that and uses it in `use_binder` in favor of `get_bounding_rect_client` directly.
Implemented and tested on the thaw/v0.5 branch because I work with leptos0.8, but there's no reason to assume it wouldn't work identically on 0.4.

Fix Follower Positioning bug in scrollable windows
